<?php
//types 1 = fixed & 2 = custome/uploder
return [
	"apiUrl" => url("Api/v1/"),
	"appUrl" => url("/"), 
	"gst"=>7,
	"firmcategories"=>[
		[
			"id"=>1,
			"name"=>"High Density Foam",
			"slug"=>"high-density-foam",
		], 
		[
			"id"=>2,
			"name"=>"Standard density foam",
			"slug"=>"Standard-density-foam",
		]
	],
	"itemitems"=>[
		[
			"id"=>1,
			"name"=>"Cover",
			"slug"=>"high-density-foam",
		],
		[
			"id"=>2,
			"name"=>"Dacron Wrap/Fill",
			"slug"=>"dacron-wrap-fill",
		]
	],
	"shapes"=>[
		[
			"id"=>1,
			"name"=>"Triangle",
			"slug"=>"triangle",
			"thumbnail"=>"triangle-foam-icon.png",
			"image"=>"Triangle-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>2,
			"name"=>"Square",
			"slug"=>"square",
			"thumbnail"=>"foam-square-icon.png",
			"image"=>"Square-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>3,
			"name"=>"Rectangle",
			"slug"=>"rectangle",
			"thumbnail"=>"Rectangle-foam-icon.png",
			"image"=>"Rectangle-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>4,
			"name"=>"Pentagon",
			"slug"=>"pentagon",
			"thumbnail"=>"Pentagon-foam-icon.png",
			"image"=>"Pentagon-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>5,
			"name"=>"Octagon",
			"slug"=>"octagon",
			"thumbnail"=>"Octagon-foam-icon.png",
			"image"=>"Octagon-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>6,
			"name"=>"L",
			"slug"=>"l",
			"thumbnail"=>"L-shape-cushion-foam-icon.png",
			"image"=>"L-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>7,
			"name"=>"T",
			"slug"=>"t",
			"thumbnail"=>"T-cushion-foam-icon.png",
			"image"=>"T-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>8,
			"name"=>"Circle",
			"slug"=>"circle",
			"thumbnail"=>"Circle-foam-icon.png",
			"image"=>"Circle-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>9,
			"name"=>"Wedge",
			"slug"=>"wedge",
			"thumbnail"=>"Wedge-cushion-foam-icon.png",
			"image"=>"Wedge-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>10,
			"name"=>"Bolster",
			"slug"=>"bolster",
			"thumbnail"=>"Bolster-Cushion-foam-icon.png",
			"image"=>"Bolster-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>11,
			"name"=>"Cylinder",
			"slug"=>"cylinder",
			"thumbnail"=>"Cylinder-foam-icon.png",
			"image"=>"Cylinder-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>12,
			"name"=>"Diamond",
			"slug"=>"diamond",
			"thumbnail"=>"Diamond-foam-icon.png",
			"image"=>"Diamond-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>13,
			"name"=>"Star",
			"slug"=>"star",
			"thumbnail"=>"Star-foam-icon.png",
			"image"=>"Star-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>14,
			"name"=>"Alberta",
			"slug"=>"alberta",
			"thumbnail"=>"Alberta-foam-icon.png",
			"image"=>"Alberta-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>15,
			"name"=>"Maple Leaf",
			"slug"=>"maple-leaf",
			"thumbnail"=>"maple-foam-icon.png",
			"image"=>"Maple-leaf-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>16,
			"name"=>"Triangle Wedge",
			"slug"=>"triangle-wedge",
			"thumbnail"=>"triangle-foam-icon.png",
			"image"=>"Triangle-shape-foam-page-icon.png",
			"type"=>1
		],
		[
			"id"=>17,
			"name"=>"Custom Size",
			"slug"=>"custom-size",
			"thumbnail"=>"Custom-foam-icon.png",
			"image"=>"",
			"type"=>2
		]

	]

];